//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDL_Task_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public int RetailerId { get; set; }
        public string RetailerCode { get; set; }
        public string RetailerName { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
